# =====================
# General Configuration
# =====================

# Path to a TLS Cert
certFile: "/path/to/cert/file.crt"  # Path to SSL certificate
keyFile: "/path/to/key/file.key"   # Path to SSL key

# Logging Level: debug, info, warn, error, dpanic, panic, fatal
logLevel: "debug"

# ===================
# Rotatorr Log Config
# ===================

logConfig:
  logOutput: "stdout"  # Options: stdout, file
  logLevel: "debug"    # Options: debug, info, warn, error, dpanic, panic, fatal
  
  # Additional log rotation options
  # filepath: "/var/log/service.log"  # Optional: File path for log output
  # filesize: 10485760  # Optional: Max log file size in bytes (10MB)
  # fileCount: 10       # Optional: Max number of log files to keep

# ==================
# Listener Config
# ==================

# Define a list of interfaces that the Proxy listens on
listeners:
  - interface: "0.0.0.0"  # Listen on all available interfaces
    port: "6001"         # TCP port

# =================
# API Upstreams
# =================

# List of API Upstreams with their settings
upstreams:
  Primary:
    type: "azure"       # API Type
    model: "default"    # Model name
    url: "http://10.10.0.127:5001"  # API URL
    priority: 1         # Priority level (lower number = higher priority)
    apiKey: "dummy"     # Replace with actual API key

  Secondary:
    type: "openai"      # API Type
    model: "default"    # Model name
    priority: 2         # Priority level (lower number = higher priority)
    apiKey: "dummy"     # Replace with actual API key

